### PR TITLE
null safety.

### PR DESCRIPTION
**Pull request by pratikpparikh**
fix for #1

### CODE REVIEW

**Comment by lexaknyazev** [comment]
Thanks for the PR. I'll review and merge it early next week.

**Comment by lexaknyazev** [comment]
Thanks again for the heads up and for drafting the NNBD support.

It seems that the upstream IDL has evolved a bit since this package was published, namely with BigInt and External References support. So my current plan is to align the bindings first and then port any remaining NNBD issues.

Since this PR was opened from the default branch, I have to close it and work on a separate one to ensure linear history. Don't worry, this won't take much time.

**Comment by pratikpparikh** [comment]
Thank you, @lexaknyazev.  Looking forward to help test this out.

**Comment by pratikpparikh** [comment]
@lexaknyazev any update on this?

**Pull request closed without merging**
